runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.APP

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*\.ts$
  - ^(.*/)?.*\.js.map$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^node_modules$
  - ^venv$
  - ^log\.txt$
  - ^\.idea$
  - ^\.git$
  - ^\.vscode$
  - ^configs$
  - venv-doc
  - ^launch\.sh$
  - ^webpack.*\.js$
  - ^(.*/)?.*\.md$